[[language]]
name = "rust"
auto-format = true
#
[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true }}

[[language]]
name = "vue"
auto-format = true
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
language-servers = [ "volar", "eslint"]
formatter = {command = 'prettier', args= ["--parser", "vue"]}
roots = ["package.json", "vue.config.js", ".prettierrc.json"]

 [language-server.volar]
 command = "vue-language-server"
 args = ["--stdio"]

 [language-server.volar.config]
 typescript = { tsdk = "./node_modules/typescript/lib" }
